=== BESTSELLER/harpocrates/.validation/schema copy 2.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "format": {
      "type": "string"
    },
    "output": {
      "type": "string"
    },
    "owner": {
      "type": "integer"
    },
    "prefix": {
      "type": "string"
    },
    "uppercase": {
      "type": "boolean"
    },
    "secrets": {
      "type": "array",
      "prefixItems": [
        {
          "type": "string"
        },
        {
          "type": "object",
          "additionalProperties": false,
          "patternProperties": {
            "^*$": {
              "type": "object",
              "additionalProperties": false,
              "properties": {
                "owner": {
                  "type": "integer"
                },
                "format": {
                  "type": "string",
                  "enum": [
                    "json",
                    "env",
                    "secret"
                  ]
                },
                "prefix": {
                  "type": "string"
                },
                "saveAsFile": {
                  "type": "boolean"
                },
                "required": [
                  "owner",
                  "prefix"
                ]
              }
            }
          }
        }
      ]
    }
  },
  "required": [
    "output",
    "secrets"
  ]
}

=== BESTSELLER/harpocrates/.validation/example.json
{
  "format": "env",
  "output": "../.tmp/",
  "owner": 123,
  "prefix": "TEST_",
  "uppercase": true,
  "secrets": [
    "secret/data/secret",
    {
      "secret/data/secret": {
        "prefix": "TEST2_",
        "format": "json",
        "filename": "test2.json",
        "owner": 2,
        "uppercase": false,
        "keys": [
          "key1",
          {
            "key2": {
              "prefix": "FIX_",
              "uppercase": false,
              "saveAsFile": true
            }
          }
        ]
      }
    }
  ]
}
